baseURL = "https://julideozcelik.com.tr"
disqusShortname = ""
googleAnalytics = "G-HBDD1RZBQ0"
languageCode = "tr"
languageName = "Tr"

paginate = "10"
summaryLength = "15"
theme = "sicily"
title = "Jülide Özçelik"

#### Sitemap
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5


[markup.goldmark.renderer]
unsafe = true
[[menu.company]]
URL = "hakkında"
name = "Hakkında"
[[menu.company]]
URL = "iletişim"
name = "iletişim"
[[menu.main]]
URL = "konserler"
name = "Konserler"
weight = 1
[[menu.main]]
URL = "hakkında"
name = "Hakkında"
weight = 2
[[menu.product]]
URL = "konserler"
name = "Konserler"
[params]
author = "Jülide Özçelik"
contact_form_action = "https://formspree.io/f/mgeqoadv"
description = "Jülide Özçelik, Türkiye'nin önde gelen caz vokalistlerinden biridir. İstanbul'da doğan sanatçı, caz müziği eğitmenliği ve sahne çalışmalarıyla bilinir. Bu websitesinde, Jülide Özçelik'in kariyeri hakkında detaylı bilgi edinebilir, konser takvimini inceleyebilir, albümlerini dinleyebilir ve kendisiyle iletişime geçebilirsiniz. Ayrıca caz müziği sevenler için öneriler ve etkinlik duyuruları da yer almaktadır"
logo = "images/logo.png"
logo_width = "200px"
[params.company]
address = ""
city = "İstanbul"
country = "Türkiye"
email = ""
phone = ""
[params.navigation_button]
enable = true
label = "İletişim"
link = "iletişim"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/custom/clean-footer.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = "julideOzcelik3.jpeg"
#[[params.footer]]
#rol_email = "pedropiedras@sicily.com"
#rol_name = "Creative Director"
#rol_representative = "Pedro Pidras"
#[[params.footer]]
#rol_email = "juanrisas@sicily.com"
#rol_name = "Chief executive officer"
#rol_representative = "Juan Risas"
#[[params.footer]]
#rol_email = "mateojosedulfo@Sicily.com"
#rol_name = "Bussines Director"
#rol_representative = "Mateo Josedulfo"
[[params.social]]
icon = "ti-facebook"
link = "https://tr-tr.facebook.com/ozcelikjulide"
title = "FACEBOOK"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/julideozcelik"
title = "TWITTER"
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/channel/UCUrZ3-1X8d2kQydL-soXPVw"
title = "YOUTUBE"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/julideozcelik/"
title = "INSTAGRAM"
